services:
  - type: web
    name: metabase
    env: docker
    plan: standard # ensure that metabase has at least 2GB of RAM (defaults to starter)
    autoDeploy: false
    envVars:
      - key: MB_DB_CONNECTION_URI
        fromDatabase:
          name: elephant
          property: connectionString
databases:
  - name: elephant
    databaseName: metabasedb
    ipAllowList: [] # only allow internal connections
